### ISSUE TITLE
World does not open with sodium-reforged

### ISSUE THREAD

**Issue by Sushant-Padha** [jediminer543/JMT-MCMT#71]
I am using Forge 36.1.30 with [MCMT](https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading/files/3355677) and [Sodium Reforged](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged/files/3376671)

When creating a new world, or opening a previously generated vanilla world, the loading screen gets stuck on 0% or 100% and never completes.

This error only occurs with both of these mods. Individually, they work.

I tried changing the config of MCMT by disabling world parallelizations, and, chunk and environment parallelizations. But it still didn't work.

```toml
[world]
	#Disable world parallelisation
	disableWorld = true
	#Disable world post tick parallelisation
	disableWorldPostTick = true
```
```toml
[misc]
	#Disable environment (plant ticks, etc.) parallelisation
	disableEnvironment = true
	#Disable parallelised chunk caching; doing this will result in much lower performance with little to no gain
	disableChunkProvider = true
```

I wonder whether these 2 mods are compatible with each other.
